repos:
- repo: local
  hooks:
    - id: check-copyright-notice
      name: check-copyright-notice
      description: Check copyright notice
      entry: python3 scripts/check_copyright_notice.py
      language: system
      files: ^(libs\/|tools\/)
      types_or: [c++, c, shell]
      exclude: |
            (?x)^(
                tools/buildmgr/test/testinput/|
                tools/packgen/test/data/|
                tools/packchk/test/data/|
                tools/projmgr/test/data/|
                libs/crossplatform/include/win|
                tools/buildmgr/cbuildgen/include/Resource.h|
                tools/packchk/include/Resource.h|
                libs/crossplatform/test/src/TestProg.cpp)
