/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 0.0.0+gcf3a3bdc
 *
 * Project: 'project.Debug+CM0' 
 * Target:  'Debug+CM0' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM0.h"



#endif /* RTE_COMPONENTS_H */
