set(CMAKE_AS_LEG_OUTPUT_EXTENSION ".o")
set(CMAKE_AS_LEG_OUTPUT_EXTENSION_REPLACE 1)

set(CMAKE_AS_LEG_COMPILE_OBJECT "<CMAKE_AS_LEG_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")

set(CMAKE_INCLUDE_FLAG_AS_LEG "-I")
