set(CMAKE_AS_GNU_OUTPUT_EXTENSION ".o")
set(CMAKE_AS_GNU_OUTPUT_EXTENSION_REPLACE 1)

set(CMAKE_AS_GNU_COMPILE_OBJECT "<CMAKE_AS_GNU_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")

set(CMAKE_INCLUDE_FLAG_AS_GNU "-I")
