set(CMAKE_AS_ARM_OUTPUT_EXTENSION ".o")
set(CMAKE_AS_ARM_OUTPUT_EXTENSION_REPLACE 1)

set(CMAKE_AS_ARM_COMPILE_OBJECT "<CMAKE_AS_ARM_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")

set(CMAKE_INCLUDE_FLAG_AS_ARM "-I")
