/*
 * CBUILDGEN generated file: DO NOT EDIT!
 * Generated by: cbuildgen version 0.0.0+gdd699a22
 *
 * Project: 'Project' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::Device:RteTest Generated Component:RteTest@1.1.0 */
#define RTE_TEST_GENERATOR


#endif /* RTE_COMPONENTS_H */
