/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.8.0
 *
 * Project: 'project.Debug+TEST_TARGET' 
 * Target:  'Debug+TEST_TARGET' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM0.h"



#endif /* RTE_COMPONENTS_H */
