/*
 * CBUILDGEN generated file: DO NOT EDIT!
 * Generated by: cbuildgen version 2.1.0-dev1
 *
 * Project: 'Target' 
 * Target:  'Target 1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "ARMCM3.h"



#endif /* RTE_COMPONENTS_H */
