name: global
on:
  pull_request:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  copyright:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden Runner
        if: ${{ !github.event.repository.private }}
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check copyright notice
        run: |
          pip install \
            pre-commit==4.5.1 \
            python-magic==0.4.24 \
            comment-parser==1.2.4
          pre-commit run --all-files
