name: global
on:
  pull_request:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  copyright:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        if: ${{ !github.event.repository.private }}
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check copyright notice
        run: |
          pip install \
            pre-commit==4.5.1 \
            python-magic==0.4.24 \
            comment-parser==1.2.4
          pre-commit run --all-files
