name: global
on:
  pull_request:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  copyright:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden Runner
        if: ${{ !github.event.repository.private }}
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check copyright notice
        run: |
          pip install \
            pre-commit \
            python-magic==0.4.18 \
            comment-parser>=1.2.3
          pre-commit run --all-files
