name: markdown
on:
  pull_request:
    paths:
      - '.github/workflows/markdown.yml'
      - '.github/markdownlint.json'
      - '.github/markdownlint.jsonc'
      - '.github/lychee.toml'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  linter:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        if: ${{ !github.event.repository.private }}
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450 # v2.19.1
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Register markdownlint warning matcher
        run: |
          echo "::add-matcher::.github/markdownlint.json"

      - name: Lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: '**/*.md'
          ignore: '**/testinput/**'
          config: '.github/markdownlint.jsonc'

      - name: Remove markdownlint warning matcher
        if: always()
        run: |
          echo "::remove-matcher owner=markdownlint::"

  check-links:
    name: Check markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devtools
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check markdown links
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --config .github/lychee.toml --verbose --no-progress './**/*.md'
          fail: true
          jobSummary: true
