name: projmgr
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/projmgr.yml'
      - '.github/matrix_includes_projmgr.json'
      - 'CMakeLists.txt'
      - 'libs/crossplatform/**'
      - 'libs/rtefsutils/**'
      - 'libs/xmlreader/**'
      - 'libs/xmltree/**'
      - 'libs/xmltreeslim/**'
      - 'tools/projmgr/**'
      - '!**/*.md'
  pull_request:
    paths:
      - '.github/workflows/projmgr.yml'
      - '.github/matrix_includes_projmgr.json'
      - 'CMakeLists.txt'
      - 'libs/crossplatform/**'
      - 'libs/rtefsutils/**'
      - 'libs/xmlreader/**'
      - 'libs/xmltree/**'
      - 'libs/xmltreeslim/**'
      - 'tools/projmgr/**'
      - '!**/*.md'
  release:
    types: [published]

jobs:
  matrix_prep:
    if: |
        (github.event_name == 'pull_request') ||
        (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/tools/projmgr/'))
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - id: set-matrix
      run: |
        publicRepo=$(echo '${{ github.event.repository.private && 'privateRepo' || 'publicRepo' }}')
        matrix=$(jq --arg publicRepo "$publicRepo" 'map(. | select((.runOn==$publicRepo) or (.runOn=="always")) )' matrix_includes_projmgr.json)
        echo "matrix={\"include\":$(echo $matrix)}\"" >> $GITHUB_OUTPUT
      working-directory: .github/
  build:
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 15
    strategy:
      fail-fast: true
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}

    steps:
      - name: Checkout devtools
        uses: actions/checkout@v3
        with:
          submodules: true

      # https://github.com/Open-CMSIS-Pack/devtools-build-action
      - name: Build
        uses: Open-CMSIS-Pack/devtools-build-action@v1.2
        with:
          target: projmgr
          arch: ${{ matrix.arch }}

      - name: Archive projmgr
        uses: actions/upload-artifact@v3
        with:
          name: projmgr-${{ matrix.target }}-${{ matrix.arch }}
          path: ./build/tools/projmgr/${{ matrix.target }}/Release/${{ matrix.binary }}
          retention-days: 1
          if-no-files-found: error

      # https://github.com/Open-CMSIS-Pack/devtools-build-action
      - name: Build swig libs windows
        if: ${{ startsWith(matrix.runs_on, 'windows') }}
        uses: Open-CMSIS-Pack/devtools-build-action@v1.2
        with:
          add_cmake_variables: -DSWIG_LIBS=ON
          add_cmake_build_args: --config Release
          arch: ${{ matrix.arch }}
          build_folder: buildswig
          target: projmgr-python

      # https://github.com/Open-CMSIS-Pack/devtools-build-action
      - name: Build swig libs macos and ubuntu amd64
        if: ${{ startsWith(matrix.runs_on, 'macos') || ( startsWith(matrix.runs_on, 'ubuntu') && matrix.arch == 'amd64' ) }}
        uses: Open-CMSIS-Pack/devtools-build-action@v1.2
        with:
          add_cmake_variables: -DSWIG_LIBS=ON
          add_cmake_build_args: --config Release
          arch: ${{ matrix.arch }}
          build_folder: buildswig
          target: projmgr-python projmgr-go

      - name: Archive projmgr swig python libs windows
        if: ${{ startsWith(matrix.runs_on, 'windows') }}
        uses: actions/upload-artifact@v3
        with:
          name: projmgr-swig-python-${{ matrix.target }}-${{ matrix.arch }}
          path: |
             ./buildswig/tools/projmgr/swig/python/projmgr.py
             ./buildswig/tools/projmgr/swig/python/_projmgr.pyd
          retention-days: 1

      - name: Archive projmgr swig python libs macos ubuntu amd64
        if: ${{ startsWith(matrix.runs_on, 'macos') || ( startsWith(matrix.runs_on, 'ubuntu') && matrix.arch == 'amd64' ) }}
        uses: actions/upload-artifact@v3
        with:
          name: projmgr-swig-python-${{ matrix.target }}-${{ matrix.arch }}
          path: |
             ./buildswig/tools/projmgr/swig/python/projmgr.py
             ./buildswig/tools/projmgr/swig/python/_projmgr.so
          retention-days: 1

      - name: Archive projmgr swig go libs macos ubuntu amd64
        if: ${{ startsWith(matrix.runs_on, 'macos') || ( startsWith(matrix.runs_on, 'ubuntu') && matrix.arch == 'amd64' ) }}
        uses: actions/upload-artifact@v3
        with:
          name: projmgr-swig-go-${{ matrix.target }}-${{ matrix.arch }}
          path: |
             ./buildswig/tools/projmgr/swig/go/projmgr.go
             ./buildswig/tools/projmgr/swig/go/projmgr.so
          retention-days: 1

  release:
    if: |
        github.event_name == 'release' &&
        startsWith(github.ref, 'refs/tags/tools/projmgr/')
    needs: [ build, unittest, coverage ]
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout devtools
        uses: actions/checkout@v3

      - name: Create distribution folders
        run: |
          mkdir -p tools/projmgr/distribution/bin tools/projmgr/distribution/lib tools/projmgr/distribution/doc tools/projmgr/distribution/etc
          cp tools/projmgr/docs/LICENSE.txt tools/projmgr/distribution/
          cp -r tools/projmgr/docs/Manual/* tools/projmgr/distribution/doc/
          cp -r tools/projmgr/schemas/* tools/projmgr/distribution/etc/
          cp -r tools/projmgr/templates/* tools/projmgr/distribution/etc/

      - name: Download projmgr linux amd64
        uses: actions/download-artifact@v3
        with:
          name: projmgr-linux64-amd64
          path: tools/projmgr/distribution/bin/linux-amd64/

      - name: Download projmgr linux arm64
        uses: actions/download-artifact@v3
        with:
          name: projmgr-linux64-arm64
          path: tools/projmgr/distribution/bin/linux-arm64/

      - name: Download projmgr macos amd64
        uses: actions/download-artifact@v3
        with:
          name: projmgr-darwin64-amd64
          path: tools/projmgr/distribution/bin/darwin-amd64/

      - name: Download projmgr windows amd64
        uses: actions/download-artifact@v3
        with:
          name: projmgr-windows64-amd64
          path: tools/projmgr/distribution/bin/windows-amd64/

      - name: Download projmgr-swig-python linux amd64
        uses: actions/download-artifact@v3
        with:
          name: projmgr-swig-python-linux64-amd64
          path: tools/projmgr/distribution/lib/linux-amd64/python/

      - name: Download projmgr-swig-python macos amd64
        if: ${{ !github.event.repository.private }}
        uses: actions/download-artifact@v3
        with:
          name: projmgr-swig-python-darwin64-amd64
          path: tools/projmgr/distribution/lib/darwin-amd64/python/

      - name: Download projmgr-swig-python windows amd64
        uses: actions/download-artifact@v3
        with:
          name: projmgr-swig-python-windows64-amd64
          path: tools/projmgr/distribution/lib/windows-amd64/python/

      - name: Download projmgr-swig-go linux amd64
        uses: actions/download-artifact@v3
        with:
          name: projmgr-swig-go-linux64-amd64
          path: tools/projmgr/distribution/lib/linux-amd64/go/

      - name: Download projmgr-swig-go macos amd64
        if: ${{ !github.event.repository.private }}
        uses: actions/download-artifact@v3
        with:
          name: projmgr-swig-go-darwin64-amd64
          path: tools/projmgr/distribution/lib/darwin-amd64/go/

      - name: Zip distribution folder
        run: zip -r projmgr.zip *
        working-directory: tools/projmgr/distribution

      - name: Attach zip archive to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/projmgr/distribution/projmgr.zip
          tag: ${{ github.ref }}
          overwrite: true
          asset_name: projmgr.zip

      - name: Download test report windows amd64
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-windows64-amd64
          path: tools/testreport/windows-amd64/

      - name: Download test report linux amd64
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-linux64-amd64
          path: tools/testreport/linux-amd64/

      - name: Download test report linux arm64
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-linux64-arm64
          path: tools/testreport/linux-arm64/

      - name: Download test report macos amd64
        if: ${{ !github.event.repository.private }}
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-darwin64-amd64
          path: tools/testreport/darwin-amd64/

      - name: Zip test reports
        run: zip -r testreport.zip *
        working-directory: tools/testreport

      - name: Attach test report archive to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/testreport/testreport.zip
          tag: ${{ github.ref }}
          overwrite: true
          asset_name: testreport.zip

      - name: Download coverage report
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: tools/coverage/

      - name: Attach coverage archive to release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tools/coverage/coverage.zip
          tag: ${{ github.ref }}
          overwrite: true
          asset_name: coverage.zip

  unittest:
    needs: matrix_prep
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}

    steps:
      - name: Checkout devtools
        uses: actions/checkout@v3
        with:
          submodules: true

      # https://github.com/Open-CMSIS-Pack/devtools-build-action
      - name: Build ProjMgrUnitTests
        uses: Open-CMSIS-Pack/devtools-build-action@v1.2
        with:
          arch: ${{ matrix.arch }}
          build_type: Debug
          target: ProjMgrUnitTests

      - name: Run projmgr unit tests
        run: |
          ctest -V -C Debug -R ProjMgrUnitTests
        working-directory: ./build

      - name: Archive unit tests results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: unittest-${{ matrix.target }}-${{ matrix.arch }}
          path: ./build/Testing/Temporary/LastTest.log
          retention-days: 1
          if-no-files-found: error

      - name: Archive gtest report
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: unit_test_result-${{ matrix.target }}-${{ matrix.arch }}
          path: ./build/test_reports/projmgrunittest-*.xml
          retention-days: 1
          if-no-files-found: error

  coverage:
    if: |
        (github.event_name == 'pull_request') ||
        (github.event_name == 'push') ||
        (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/tools/projmgr/'))
    env:
        lcov_base: https://github.com/linux-test-project/lcov/releases/download/v1.15/
        lcov_installer: lcov-1.15.tar.gz
        cov_retention_days: 1
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Install linux deps
        run: |
          sudo apt update
          sudo apt-get install \
            lcov

      - name: Checkout devtools
        uses: actions/checkout@v3
        with:
          submodules: true

      # https://github.com/Open-CMSIS-Pack/devtools-build-action
      - name: Build ProjMgrUnitTests
        uses: Open-CMSIS-Pack/devtools-build-action@v1.2
        with:
          add_cmake_variables: -DCOVERAGE=ON
          arch: amd64
          build_type: Debug
          target: ProjMgrUnitTests

      - name: Run ProjMgrUnitTests
        run: |
          ctest -V -C Debug -R ProjMgrUnitTests
        working-directory: ./build

      # Needs to be removed once the bug is resolved
      # lcov reporting 1.14 on 1.15 version
      # https://groups.google.com/g/linux.debian.bugs.dist/c/a9SZGCENJ2s?pli=1
      - name: Setup lcov1.15
        run: |
          wget -q ${{ env.lcov_base }}/${{ env.lcov_installer }}
          tar -xvf ${{ env.lcov_installer }}
        working-directory: ./build/tools/projmgr

      - name: Generate coverage report
        run: |
          lcov-1.15/bin/lcov --rc lcov_branch_coverage=1 --rc geninfo_no_exception_branch=1 -c --directory . --output-file full_coverage.info
          lcov-1.15/bin/lcov --rc lcov_branch_coverage=1 --rc geninfo_no_exception_branch=1 -e full_coverage.info '/tools/projmgr/include/*' '*/tools/projmgr/src/*' -o coverage.info
          genhtml coverage.info --output-directory coverage --branch-coverage
          zip -r coverage.zip coverage/*
        working-directory: ./build/tools/projmgr/

      - name: Upload Report to Codecov
        if: ${{ !github.event.repository.private }}
        uses: codecov/codecov-action@v3
        with:
          files: ./build/tools/projmgr/coverage.info
          fail_ci_if_error: true
          flags: projmgr-cov
          functionalities: fix

      - name: Determine retention days
        if: (github.event_name == 'push')
        run: |
          echo "cov_retention_days=7" >> $GITHUB_ENV

      - name: Archive coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            ./build/tools/projmgr/coverage.zip
            ./build/tools/projmgr/coverage.info
          retention-days: ${{ env.cov_retention_days }}
          if-no-files-found: error

  test-results-preparation:
    name: "Publish Tests Results"
    needs: [ unittest ]
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Download unit test report windows
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-windows64-amd64
          path: testreports/

      - name: Download unit test report linux amd64
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-linux64-amd64
          path: testreports/

      - name: Download unit test report linux arm64
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-linux64-arm64
          path: testreports/

      - name: Download unit test report macos
        if: ${{ !github.event.repository.private }}
        uses: actions/download-artifact@v3
        with:
          name: unit_test_result-darwin64-amd64
          path: testreports/

      - name: Event File
        uses: actions/upload-artifact@v3
        with:
          name: Event File
          path: ${{ github.event_path }}
