name: setup_env

on:
  workflow_call:
    outputs:
      nightly:
        value: ${{ jobs.setup.outputs.nightly }}
      retention_days:
        value: ${{ jobs.setup.outputs.retention_days }}

jobs:
  setup:
    name: Set environment
    runs-on: ubuntu-latest
    outputs:
      nightly: ${{ steps.check-nightly.outputs.nightly }}
      retention_days: ${{ steps.check-nightly.outputs.retention_days }}
    steps:
      - name: Check Nightly/Scheduled
        id: check-nightly
        run: |
          echo "nightly=$(echo '${{ (github.event.schedule && (!github.event.repository.private)) && 'true' || 'false' }}')" >> $GITHUB_OUTPUT
          echo "retention_days=7" >> $GITHUB_OUTPUT